baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Coffie Portfolio'
theme = "basic"

[params]
  author = "Brain Hogan"
  description = "My portfolio site"


gh_url = "https://api.github.com/users"
gh_user = "rcoffie"

pygmentsUseClasses = true
  
[permalinks]
  posts = "posts/:year/:month/:slug/"
  year = "/posts/:slug/"
  month = "/posts/:slug/"

[taxonomies]
  year = "year"
  month = "month"
  tag = "tags"
  category = "categories"